---=====================================
---THAIC Localization Dialog
---东方梦摇篮本土化 对话
---=====================================

--[[
For translaters:
This is the dialog file of THAIC.
Only the contents in `text` need to be translated. Change other code can lead to error.
The code in `<>` is text effect. To change text effect, see `AiC_text_effect.lua`.
给翻译者：
这是东方梦摇篮的对话文件。
只有`text`中的内容需要被翻译。更改其他代码可能引发错误。
`<>`中的代码是文字效果。要更改文字效果，参见`AiC_text_effect.lua`。
--]]

---There may be 'a little' error in multi-text-effect(it will sub by 1 in some situation),
---but I believe that you can solve it(Please try to change range and extend for serveral times,you can do it lol).
---多文字效果的范围可能有一点“小”错误(在某些情况下会差一)，
---不过我相信你们可以解决的www（多调几次范围和extend，总能试出来的）

local lib = aic.l10n.dialog

---道中boss前对话
---Dialog before middle boss
lib.dialog0 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.5,
    vscale = 0.5,
    vol = 1,
    name = '阿尔玛・奥普菲帕姆',
    snd = "se:Muki_AiC_dialog_Alma",
    img = {
        "image:Muki_AiC_Alma_face_default",
    },
    text = {
        '！！！',
        '难道说……',
        '我不会让你去找诺艾儿同学的！',
    }
}

---战斗前对话
---Dialog before battle
lib.dialog1 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.5,
    vscale = 0.5,
    vol = 1,
    name = '诺艾儿·柯涅尔',
    snd = "se:Muki_AiC_dialog_Noel",
    img = {
        "image:Muki_AiC_Noel_face_default",
        "image:Muki_AiC_Noel_face_default",
        "image:Muki_AiC_Noel_face_fight"
    },
    text = {
        '呼……好累……\n呼……',
        '呼……\n等一下，那个是……\n难道说你就是<Color {255,255,0,0}>厨圣</Color>？',
        '终于找到你了！\n之前对我做了那么多<Color {255,255,0,0}>过分的事情</Color>……',
        '<shake 3>这次我可不会坐以待毙了！ </shake>'
    }
}

---伊夏入场对话
---Ixia entering dialog
lib.dialog2 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.5,
    vscale = 0.5,
    vol = 1,
    name = {
        '伊夏·波利斯塔切尔',
        '伊夏·波利斯塔切尔',
        '诺艾儿·柯涅尔',
        '诺艾儿·柯涅尔',
        '伊夏·波利斯塔切尔',
    },
    snd = {
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia"
    },
    img = {
        "image:Muki_AiC_Ixia_face_surprise",
        "image:Muki_AiC_Ixia_face_notworryyou",
        "image:Muki_AiC_Noel_face_smile3",
        "image:Muki_AiC_Noel_face_normal",
        "image:Muki_AiC_Ixia_face_angry",
        "image:Muki_AiC_Ixia_face_default"
    },
    text = {
        '<shake 3>诺艾儿·柯涅尔！</shake>总算找到你了！\n真是担心死……',
        '不，我才没有<Color {255,255,0,0}>很担心你</Color>！',
        '……谢谢你，伊夏同学。',
        '不过，\n你还没从那次<Color {255,255,0,0}></Color 3><uppertext 森林领主>大</uppertext>型魔物的袭击中恢复过来吧……',
        '绝对没问题！就让我来帮你解决它吧！',
        '就是你这家伙一直在欺负诺艾儿吧？\n<shake 3>我绝对不会放过你的！ </shake>'
    },
    num = { 1, 1, 2, 2, 1 }
}

---普莉姆拉入场对话
---Primula entering dialog
lib.dialog3 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = { 0.6, 0.6, 0.5, 0.6, 0.6, 0.5, 0.5 },
    vscale = { 0.6, 0.6, 0.5, 0.6, 0.6, 0.5, 0.5 },
    vol = 1,
    name = {
        '普莉姆拉',
        '普莉姆拉',
        '诺艾儿·柯涅尔',
        '普莉姆拉',
        '普莉姆拉',
        '伊夏·波利斯塔切尔',
        '诺艾儿·柯涅尔',
    },
    snd = {
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
    },
    img = {
        "image:Muki_AiC_Primula_face_fight",
        "image:Muki_AiC_Primula_face_fight",
        "image:Muki_AiC_Noel_face_understand",
        "image:Muki_AiC_Primula_face_fight",
        "image:Muki_AiC_Primula_face_fight",
        "image:Muki_AiC_Ixia_face_notworryyou",
        "image:Muki_AiC_Noel_face_thinking",
    },
    text = {
        '诺艾儿！\n怎么可以独自一人来挑战这种<Color {255,255,0,0}></Color 2><uppertext 厨圣>敌人</uppertext>呢！',
        '还有伊夏！\n你们先撤退，这里老师来想办法！',
        '可是老师……\n您不是不能战斗吗？',
        '「只要能打中它就行了！」\n<Color {255,255,0,255}>那位女士</Color>是这么说的……',
        '如果是这样的话，\n老师对自己的准头还是有信心的！',
        '<scale 0.75>诺艾儿……就这样丢下老师也不好……\n我们先躲起来观察情况吧。</scale>',
        '<scale 0.75>嗯。</scale>',
    },
    num = { 1, 1, 2, 1, 1, 3, 2 }
}

---获取魔法前对话
---Dialog before getting magic
lib.dialog4 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = { 0.6, 0.5, 0.6, 0.5, 0.6 },
    vscale = { 0.6, 0.5, 0.6, 0.5, 0.6 },
    vol = 1,
    name = {
        '普莉姆拉',
        '伊夏·波利斯塔切尔',
        '普莉姆拉',
        '诺艾儿·柯涅尔',
        '普莉姆拉'
    },
    snd = {
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Noel"
    },
    img = {
        "image:Muki_AiC_Primula_face_fight",
        "image:Muki_AiC_Ixia_face_surprise",
        "image:Muki_AiC_Primula_face_surprise",
        "image:Muki_AiC_Noel_face_lose",
        "image:Muki_AiC_Primula_face_teach3",
        "image:Muki_AiC_Primula_face_teach",
        "image:Muki_AiC_Primula_face_teach2",
        "image:Muki_AiC_Primula_face_memory",
    },
    text = {
        '不行……\n这个区域的空气中的<uppertext MP></uppertext 1><Color {255,170,160,247}>魔</Color>力基本消耗完了……',
        '老师！您还好吗？',
        '诺艾儿和伊夏？ \n我不是叫你们赶紧走吗？',
        '我们没法把您丢在这里不管……',
        '算了……\n我还有最后一招。',
        '刚才路上有一位女士给了我这个……\n似乎是<Color {255,255,0,0}>非官方魔法认证装置。</Color>',
        '它的认证手续没有那么复杂，\n但同时也只能提供<Color {255,255,0,0}>临时认证</Color>。',
        '不过用来完成这场战斗应该是足够了……\n诺艾儿同学，现在只能靠你了。\n我先带伊夏同学到安全的地方。',
    }
}

---获取魔法后对话
---Dialog after getting magic
lib.dialog5 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.5,
    vscale = 0.5,
    vol = 1,
    name = '诺艾儿·柯涅尔',
    snd = "se:Muki_AiC_dialog_Noel",
    img = {
        "image:Muki_AiC_Noel_face_embarassed",
        "image:Muki_AiC_Noel_face_lose",
        "image:Muki_AiC_Noel_face_lose2",
    },
    text = {
        '这……这是什么东西？\n好……好厉害……',
        '感觉被灌输了很多<uppertext 符卡></uppertext 1><Color {255,255,0,0}>记</Color>忆……',
        '不过没时间犹豫了……\n我必须要保护老师和伊夏同学！'
    }
}

---圣光爆发前对话
---Dialog before burst
lib.dialog6 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.5,
    vscale = 0.5,
    vol = 1,
    name = '诺艾儿·柯涅尔',
    snd = "se:Muki_AiC_dialog_Noel",
    img = {
        "image:Muki_AiC_Noel_face_lose",
        "image:Muki_AiC_Noel_face_lose",
        "image:Muki_AiC_Noel_face_fight"
    },
    text = {
        '<shake 3>老师……\n伊夏同学…… </shake>',
        '<shake 3>难道……结局已经无法改变了吗…… </shake>',
        '<shake 5>不……\n就算我死了也没关系，\n但我绝对不能让老师和伊夏遭到你的毒手！ </shake>'
    }
}

---最终阶段前对话
---Dialog before last phase
lib.dialog7 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.5,
    vscale = 0.5,
    vol = 1,
    name = {
        '诺艾儿·柯涅尔',
        '？？？',
        '？？？',
        '？？？',
        '诺艾儿·柯涅尔',
        '诺艾儿·柯涅尔',
        '诺艾儿·柯涅尔',
        '？？？？？？',
    },
    snd = {
        "se:Muki_AiC_dialog_Noel",
        'plst00',
        'plst00',
        'plst00',
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        'plst00',
    },
    img = {
        "image:Muki_AiC_Noel_face_lose4",
        "image:Muki_AiC_Yukari_face_default",
        "image:Muki_AiC_Yukari_face_fight",
        "image:Muki_AiC_Yukari_face_smile",
        "image:Muki_AiC_Noel_face_understand",
        "image:Muki_AiC_Noel_face_default",
        "image:Muki_AiC_Noel_face_fight",
        "image:Muki_AiC_Okina_face_default",
    },
    text = {
        '……',
        '<Color {255,255,0,255}>真是执着的少女呢\n不过你还没有领悟到弹幕的精髓啊</Color>',
        '<Color {255,255,0,255}>就再给你一次机会吧\n用我的力量</Color>',
        '<Color {255,255,0,255}>事情变得有趣起来了呢</Color>',
        '诶？\n身上的伤……突然不疼了……',
        '虽然不知道您是谁，\n但我十分感谢……',
        '我<scale 1.25></scale7><color 0xFFFF0000></color7><Uppertext {学园的才女,0,5}>诺艾儿·柯涅尔</Uppertext>，\n</wait>发誓将战斗至最后一刻！',
        '<Color {255,255,150,0}>哎呀，这样可就不公平了</Color>',
        '<Color {255,255,150,0}>屏幕那边那个，\n你就用我的力量吧</Color>',
        ---秘仪之力获取动画
        ---Power of Secret Ceremony Getting Animation
    },
    --num = { 1, 2, 2, 2, 1, 1, 1, 3 } --这里将三人立绘分开的观感不太好
}

---最终阶段前对话
---Dialog before last phase
lib['dialog7.5'] = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.3,
    vscale = 0.3,
    vol = 1,
    name = '诺艾儿·柯涅尔',
    snd = "se:Muki_AiC_dialog_Noel",
    img = "image:Muki_AiC_Noel_face_final",
    text = { "沉眠于摇篮吧，境界外的魔物！" }, --因为未知的原因text必须放在表里
}

---LSC对话
---Dialog of Last Spellcard
lib.dialog8 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.3,
    vscale = 0.3,
    vol = 1,
    name = '诺艾儿·柯涅尔',
    snd = "se:Muki_AiC_dialog_Noel",
    img = "image:Muki_AiC_Noel_face_final",
    text = {
        ---LSC开始前
        ---Before last spellcard
        '……',
        '说实话，我对<color 0xFFFF0000>你</color>如何能面不改色地\n做出这些事情多少有点好奇。',
        '<color 0xFFFF0000>你</color>难道从来没有想过我的感受吗？\n还是说<color 0xFFFF0000>你</color>color 0xFFFF00FF>以此为乐？</color>',
        '那些都无所谓了。\n现在，我要直接对你发起挑战。',
        '<color 0xFFFF0000>“可怜即可爱”</color>，是吗？\n<color 0xFFFF0000>你</color>是抱持着这样的心态来折磨我的吗？',
        '在你找上我之前，\n又有多少个<color 0xFFFF0000>天真无知</color>的<color 0xFFFF0000>少女</color>因为你饱受折磨？',
        '<shake 3></shake 7><color 0xFFFF0000>给我下地狱吧。</color>',
        '<color 0xFFFF0000>你</color>觉得打败我就会结束这一切吗？\n那可太便宜<color 0xFFFF0000>你</color>了。',
        '即使我和她们会忘记这一切，\n<color 0xFFFF0000>你</color>却不会忘记。',
        '希望<color 0xFFFF0000>你</color>关掉<color 0xFFFF0000>游戏</color>后\n今天晚上能带着这些话安心入睡。',
        '是时候进行最后的对决了。',
        '<scale 1.5></scale 13><color 0xFFFF0000>「逆转现实与幻想的境界」！</color>',
    },
}

---战斗结束后对话（玩家完成最终阶段且未触发LSC时出现）
---Dialog after battle (Appear if player finish last phase and Last Spellcard is not triggered)
lib.dialog9 = {
    pos = 'right',
    canskip = false,
    t = 120,
    hscale = 0.5,
    vscale = 0.5,
    vol = 1,
    name = '梅法·格里亚德',
    snd = "se:Muki_AiC_dialog_Mepha",
    img = {
        "image:Muki_AiC_Mepha_face_smile",
        "image:Muki_AiC_Mepha_face_smile",
        "image:Muki_AiC_Mepha_face_default",
        "image:Muki_AiC_Mepha_face_default",
        "image:Muki_AiC_Mepha_face_fight"
    },
    text = {
        '刚才不知怎的突然就来到这里了……\n不过看来是来对了呢。',
        '诺艾儿·柯涅尔，\n贝尔米特国立大学所属，\nⅢ级士官候补生……\n我没记错吧？',
        '真是相当精彩的战斗……\n你已经做得足够好了。',
        '我向你保证，\n你和你的朋友一定能安全到家。',
        '……你是什么<color 0xFFFF0000>魔物</color>呢？\n抱歉，我看不出来。',
        '不过有一点可以确定……\n我会让你吃到苦头的，你这<color 0xFFFF0000>畜生</color>。'
    }
}

---真结局对话（玩家在最终阶段中失败或续关后通关时出现）
---Dialog of True Ending（Appear if player fail in last phase or finish game after Continue）
lib.dialog_true_ending = { 
    snd = {
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Noel",
        "plst00",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "plst00",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Primula",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "plst00",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "se:Muki_AiC_dialog_Laevigata",
        "plst00",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "plst00",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "plst00",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Ixia",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Noel",
        "se:Muki_AiC_dialog_Ixia",
        "plst00",
        "plst00",
        "plst00",
    },
    img = 'img_void',
    text = {
        '诺艾儿「呼……',
        '　　　　终于倒下了吗……」',
        '普莉姆拉「看来是这样……',
        '　　　　　我真不敢想象你居然能击败如此强大的敌人，诺艾儿。」',
        '普莉姆拉「你刚才战斗的样子，',
        '　　　　　颇有几分夏丝塔女士的风貌呢……」',
        '诺艾儿「谢…谢谢老师……」',
        '这时伊夏醒来了。',
        '伊夏「唔…诺艾儿…？诺艾儿同学！',
        '　　　你还好吗？那个混蛋怎么样了？」',
        '诺艾儿「你先冷静，伊夏同学……',
        '　　　　你的身体还很虚弱，得多休息才行。」',
        '诺艾儿「那个厨圣已经被打败了，',
        '　　　　现在我们应该安全了……」',
        '伊夏「要不是本小姐身体还没恢复，',
        '　　　终结那个魔物的就是我了。」',
        '伊夏「又被你抢先了，真不甘心……」',
        '诺艾儿「其实它不是魔物……算了，区别不大。」',
        '普莉姆拉「时间不早了，我送你们回家吧。',
        '　　　　　伊夏同学，你还走得动吗？」',
        '伊夏「当然！',
        '　　　嘶…好痛……」',
        '诺艾儿「这种时候就别逞强了，伊夏同学。」',
        '诺艾儿将伊夏背起来。',
        '伊夏「咿呀！',
        '　　　诺——诺艾儿，你干什么？」',
        '伊夏『好…好近……',
        '　　　这个距离的话，连诺艾儿身上的味道也——』',
        '诺艾儿「把你送回去啊。',
        '　　　　你都不能走路了，不是只能这样了吗？」',
        '普莉姆拉『我本来想用魔法把伊夏同学搬回去，',
        '　　　　　现在看来是没这个必要了呢。呵呵……』',
        '普莉姆拉「现在时间太晚了，',
        '　　　　　回格拉提亚要经过很多魔族的领地，',
        '　　　　　你们这个样子无法战斗，实在太危险了。」',
        '普莉姆拉「不然伊夏同学就在诺艾儿家暂住一晚如何？',
        '　　　　　我会联系你父母的。」',
        '伊夏「那…那也没办法了，',
        '　　　毕竟老师都这么说了……」',
        '诺艾儿「伊夏同学，',
        '　　　　你想去我家的心情可都写在脸上了哦？」',
        '伊夏「才…才没有……！',
        '　　　本小姐大驾光临，你应该感到荣幸才对！」',
        '普莉姆拉「伊夏同学这样的性格还真是可爱呢。',
        '　　　　　加油哦，诺艾儿，老师先回去了。',
        '　　　　　不用担心我，我有办法不惊动路上的魔族。」',
        '伊夏「等等，',
        '　　　『加油』是什么意思？」',
        '——半个标准时后',
        '诺艾儿「我回来了，姐姐。」',
        '丽薇歌塔「欢迎回来，诺艾儿~',
        '　　　　　哎呀，那个是……？」',
        '丽薇歌塔「伊夏小姐？',
        '　　　　　你们这么快就发展到这一步了吗……」',
        '丽薇歌塔「不过反正诺艾儿已经成年了，',
        '　　　　　想要做什么也是你们的自由呢~」',
        '诺艾儿「我们才不是你想象的那种关系……',
        '　　　　伊夏同学只是在我们家留宿一晚而已。」',
        '伊夏「对啊…才…才不是……」',
        '诺艾儿『怎么感觉她很失望似的……』',
        '丽薇歌塔「嗯…嗯~嗯。姐姐知道了。',
        '　　　　我去给你们准备洗澡水。」',
        '丽薇歌塔『看来是还差临门一脚呢。',
        '　　　　　那我就来帮伊夏小姐一把吧……』',
        '——浴室中',
        '伊夏『这个味道……有点辣辣的。',
        '　　　应该是诺艾儿姐姐准备的香薰吧……』',
        '诺艾儿「……」',
        '伊夏「诺艾儿！你在看哪呢！色鬼！」',
        '诺艾儿「抱歉……',
        '　　　　我在想，伊夏同学和上次来的时候比好像没什么变化呢。」',
        '伊夏「笨蛋！你不也……',
        '　　　诶？！诺艾儿你你你什么时候……这么大了？」',
        '诺艾儿「这么说的伊夏同学才是色鬼吧。」',
        '伊夏「笨蛋！笨蛋笨蛋笨蛋……」',
        '诺艾儿「伊夏同学愿意怎么叫我都行，但把手一直放在我胸上是不是……」',
        '伊夏「……笨蛋。」',
        '诺艾儿「……伊夏同学？」',
        '伊夏「那个，诺艾儿……',
        '　　　叫我伊夏就行了。」',
        '诺艾儿「如果伊夏同学…',
        '　　　　如果伊夏愿意的话，当然没问题。」',
        '伊夏「……」',
        '诺艾儿「再泡的话就要泡晕了。',
        '　　　　我们出去吧，伊夏？」',
        '伊夏「……嗯。」',
        '——诺艾儿房间',
        '诺艾儿「我房间里没有沙发，只有这一张床……',
        '　　　　所以要麻烦伊夏和我一起挤一张床了，可以吗？」',
        '伊夏「当……当然可以！',
        '　　　……」',
        '诺艾儿「……这个表情，伊夏还在烦恼着什么吧。',
        '　　　　可以告诉我吗？」',
        '伊夏「……我在想，',
        '　　　果然我还是追不上诺艾儿呢。」',
        '诺艾儿「伊夏……？」',
        '伊夏「最近每次考试我都比不上你……',
        '　　　遇到强大的魔族也还要靠你才能打败。」',
        '伊夏「即使我再怎么努力……',
        '　　　到最后还是会被身为『学园的才女』的你的光芒掩盖。」',
        '诺艾儿「不要这么说，伊夏。',
        '　　　　你还记得我们第一次见面的时候吗？」',
        '伊夏「诶？为什么突然提到这个……」',
        '诺艾儿「最开始、拥有『学园的才女』这个称号的，是伊夏你哦。',
        '　　　　而我甚至连最基本的『纯白之弓』都没掌握。」',
        '诺艾儿「就在我想要放弃的时候……',
        '　　　　是伊夏你来主动帮助我。」',
        '诺艾儿「我至今还清楚地记得那一幕——',
        '　　　　你握着我的手，让我第一次用出了那个魔法……」',
        '伊夏「可是后来我不是跟你说了吗……',
        '　　　那次的『纯白之弓』其实是我咏唱的。」',
        '诺艾儿「但如果没有伊夏的话——',
        '　　　　也许那时我就退学了呢。」',
        '诺艾儿「之后也是靠伊夏你无微不至的辅导，',
        '　　　　我才能有现在的成绩。」',
        '诺艾儿「虽然把我当作『劲敌』，',
        '　　　　却一直在帮助我。」',
        '诺艾儿「尽管伊夏嘴上不饶人，',
        '　　　　实际上很温柔呢。」',
        '诺艾儿「既然我追不上你时你都停下来等我了，',
        '　　　　现在我又有什么理由不等你呢？」',
        '诺艾儿「今后的日子里，',
        '　　　　就让我们一同前进吧。」',
        '伊夏「诺艾儿……」',
        '诺艾儿「伊夏……」',
        '伊夏「那…那个……诺艾儿……」',
        '诺艾儿「伊夏？」',
        '伊夏「该…该说那句话了吧……」',
        '诺艾儿「…什么话？」',
        '伊夏「笨蛋…！我说就是了！',
        '　　　我喜欢你，诺艾儿！」',
        '诺艾儿「诶？我，我也喜欢你——」',
        '伊夏『啊啊……果然是这样吗……',
        '　　　既然这样……』',
        '伊夏把诺艾儿揽入怀中，双唇相贴。',
        '伊夏「我对你的喜欢，是想要这样做的喜欢哦。」',
        '伊夏「我最喜欢诺艾儿了……',
        '　　　所以，可以和我交往吗……」',
        '诺艾儿「诶……诶？',
        '　　　　交往？我…和伊夏同……伊夏？」',
        '伊夏「果然还是不行吗……',
        '　　　抱…抱歉，就当我什么都——」',
        '诺艾儿「可以哦。',
        '　　　　如果是伊夏的话……」',
        '诺艾儿「恋爱什么的，我不是很清楚……',
        '　　　　总感觉这种事情离我很远呢。」',
        '诺艾儿「姐姐说你喜欢我的时候，我还不太相信来着……」',
        '诺艾儿「但如果伊夏真的这么喜欢我，我当然不会拒绝伊夏。」',
        '诺艾儿「……因为我希望——',
        '　　　　伊夏能一直幸福快乐。」',
        '伊夏「…我…我也是！',
        '　　　我会让诺艾儿幸福的！」',
        '伊夏「总会有一天，我会让你说出『我喜欢你』的！',
        '　　　你可要做好觉悟哦？」',
        '诺艾儿「嗯。我会期待的，那一天的到来。',
        '　　　　伊夏你身体还没恢复，早点休息吧。」',
        '诺艾儿「晚安。」',
        '伊夏「晚…晚安。」',
        'TRUE ENDING 只要你在身边',
        'Congratulation！不打败诺艾儿，才是真正的好结局！',
        '今后也请各位善待诺艾儿，不要再让她受伤了！'
    }
}
